// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Theme } from "../theme.slint";
import { Images } from "../images.slint";
import { Page } from "page.slint";
import { IconButton } from "../widgets/widgets.slint";
import { GroupBox } from "../widgets/group_box.slint";

export component Guestos inherits Page {
    in property <string> gname;
    in-out property <image> gimage: Images.guestos_kylin;
    in property <string> gstatus;
    in property <string> id;
    callback set-gimage();

    set-gimage() => {
        if gstatus == "running" {
            gimage = Images.guestos_kylin;
        } else if gstatus == "busy" {
            gimage = Images.guestos_kylin_busy
        } else {
            gimage = Images.guestos_kylin_offline;
        }

    }

    GroupBox {
        VerticalLayout {
            vertical-stretch: 1;
            spacing: Theme.spaces.medium;
            alignment: start;

            Image {
                //vertical-stretch: 0;
                preferred-height: 550px;
                //source: Images.guestos_kylin;
                source: gimage;
            }

            Text {
                vertical-stretch: 0;
                horizontal-alignment: center;
                text: gname;
                color: Theme.palette.slint-blue-100;
                font-size: Theme.typo.header-item.size;
                font-weight: Theme.typo.header-item.weight;
                wrap: word-wrap;
                width: 150px;
                //height: 100%;
            }

            // spacer
            Rectangle {
                vertical-stretch: 1;
            }
        }
    }
}
