import { Button, VerticalBox, LineEdit, CheckBox,Spinner } from "std-widgets.slint";
import { Theme } from "../theme.slint";
import { Images } from "../images.slint";

export component LoginWindow inherits Window {
    //background: Images.login;
    background: #f8f9fa;
    Image {
        preferred-width: 800px;
        preferred-height: 440px;
        source: Images.login;
        //x: 0px;
        //y: 0px;
    }
    
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
           Text {
                text: "登录云桌面";
                font-size: 24px;
                color: white;
                horizontal-alignment: center;
                font-weight: 1000;                
           }
        }
        Row {
            LineEdit { // Username
                horizontal-alignment: left;
                font-size: 16px;
                placeholder-text: "用户名";
                height: 35px;
            }
        }
        Row {
            LineEdit { // Password
                horizontal-alignment: left;
                font-size: 16px;
                placeholder-text: "密码";
                input-type: password;
                height: 35px;
            }
        }
        CheckBox {
            height: 35px;
            horizontal-stretch: 1;
            text: "保存密码?";


        }    
        Row{
            Button {
                text: "登录";
                primary: true;
                height: 35px;

        }
    }
}
}
