import { VerticalBox , HorizontalBox, Button} from "std-widgets.slint";
import { Button, VerticalBox, LineEdit, CheckBox,Spinner } from "std-widgets.slint";
import { BorderlessWindow } from "borderless-window.slint";
import { Images } from "../../ui/images.slint";

export global Display {
    // 导出全局单例：Rust代码可以操作
    callback xview_display();
}  
export component LoginWindow inherits BorderlessWindow {
    title: "欢迎登录云桌面";
    preferred-width: 800px;
    preferred-height: 440px;
    
/*
    Image {
        preferred-width: 480px;
        preferred-height: 330px;
        source: Images.login;
        //x: 0px;
        //y: 0px;
    }
    */

    callback close-window();
    callback hidden-window();
    //callback minimized-window(bool);
    //callback maximized-window(bool);
    //callback move-window(length, length);
    //callback mouse-down(int, int);
    //callback mouse-move(int, int);

    on-close-window() => {
        close-window();
    }

    hidden-window => {
        self.title = "隐藏窗口";
        self.height = 10px;
        self.width = 10px;
        
    
    }
 /*
    on-minimized-window(enable) => {
        minimized-window(enable);
    }

    on-maximized-window(enable) => {
        maximized-window(enable);
    }

    on-move-window(offset-x, offset-y) => {
        move-window(offset-x, offset-y);
    }
    
*/
    GridLayout {
        x: 400px;
        padding: 50px;
        spacing: 25px;
        Row {
           Text {
                text: "登录云桌面";
                font-size: 24px;
                color: white;
                horizontal-alignment: left;
                font-weight: 1000;                
           }
        }
        Row {
            LineEdit { // Username
                horizontal-alignment: left;
                font-size: 16px;
                placeholder-text: "用户名";
                height: 35px;
                colspan: 2;
            }
        }
        Row {
            LineEdit { // Password
                horizontal-alignment: left;
                font-size: 16px;
                placeholder-text: "密码";
                input-type: password;
                height: 35px;
                colspan: 2;
            }
        }
        CheckBox {
            height: 35px;
            horizontal-stretch: 1;
            text: "保存密码?";

        }    
        Row{
            Button {
                text: "登录";
                primary: true;
                height: 35px;
                clicked => {
                    //close-window();
                    hidden-window();
                    Display.xview_display();
                    close-window();
                }

        }
    }
}
}