// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Theme, ScreenSize } from "theme.slint";
import { BarTileModel } from "widgets/widgets.slint";
import { Images } from "images.slint";
import { Theme } from "theme.slint";
import { Navigation, MenuButton, Menu, Value } from "widgets/widgets.slint";
import { BalanceAdapter, OverviewAdapter, UsageAdapter, WeatherAdapter, MenuPageAdapter, MenuOverviewAdapter, SettingsAdapter } from "pages/pages.slint";
import { KioskOverlay } from "blocks/kiosk_overlay.slint";
import { Header, HeaderAdapter } from "blocks/blocks.slint";
import { Menu, PageScrollView, PageContainer } from "widgets/widgets.slint";
import { Balance, Overview, Usage, UsageAdapter, Weather, About } from "pages/pages.slint";
import { Guestos } from "pages/guestos.slint";
import { LoginWindow } from "pages/login.slint";
import { BarBackground } from "widgets/chart_pattern.slint";

export { OverviewAdapter, UsageAdapter, Value, WeatherAdapter, MenuPageAdapter, MenuOverviewAdapter, SettingsAdapter,
    BarTileModel, Images, HeaderAdapter }

export global VDIClient {
    //in property <[guestos_data]> name;
    // 导出全局单例：Rust代码可以操作
    callback xview_connect(string, string);
    callback guestosRunning(string) -> bool;
}    

// Added:
export struct guestos_data {
    gid: string,
    gname: string,
    guri: string,
    gstatus: string,
}

export component MainWindow inherits Window {

    title: "";
    icon: Images.logo;
    min-width: 1680px;
    min-height: 480px;
    background: Theme.palette.pure-black;
    preferred-height: 700px;
    //preferred-width: 1920px;
    preferred-width: 100%;

    in property <string> date;
    in property <string> uname;    
    in property <[guestos_data]> myguestos: [
        { gid: "i-000001", gname: "综合桌面", guri: "spice://192.168.10.1:5905", gstatus: "running"},
        { gid: "i-00000F", gname: "分析桌面", guri: "spice://192.168.10.1:5903", gstatus: "Shu"},
    ];

    // 更新当前登录的虚拟机状态
    callback update_state(string);

    Rectangle {
        //width: root.width;
        background: Theme.palette.background-gradient;

        VerticalLayout {
            padding-bottom: 50px;
            Header {
                uname: root.uname;
                date: root.date;
            }
            
            HorizontalLayout {
                vertical-stretch: 1;
                spacing: 25px;
                padding-left: 25px;
                padding-right: 25px;
                width: 1680px;
                //opacity: selection != -1 ? 0 : 1;
                //animate opacity { duration: Theme.durations.medium; }

                PageScrollView {
                    
                    for tile[i] in myguestos : PageContainer {
                        PageContainer {
                            clicked => { 
                                // 更新虚拟机状态
                                root.update_state(myguestos[i].gid);

                                // 进入远程桌面
                                VDIClient.xview_connect(myguestos[i].guri, myguestos[i].gname); 

                            }
    
                            Guestos {
                                gname: myguestos[i].gname;
                                gstatus: myguestos[i].gstatus;

                                init => {
                                    // 设置虚拟机状态
                                    self.set-gimage();
                                }
                            }       
                        }//PageContainer
                    }//for
                }//PageScrollView
            }//HorizontalLayout
        }
    }
}

