// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

export global Images {
    in property <image> arrow-left: @image-url("assets/arrow-left.svg");
    in property <image> arrow-right: @image-url("assets/arrow-right.svg");
    in property <image> check: @image-url("assets/check.svg");
    in property <image> sunny: @image-url("assets/sunny.svg");
    in property <image> cloud: @image-url("assets/cloud.svg");
    in property <image> cloudy: @image-url("assets/cloudy.svg");
    in property <image> settings: @image-url("assets/settings.svg");
    in property <image> information: @image-url("assets/information.svg");
    in property <image> slint-logo: @image-url("assets/slint-logo-simple-dark.svg");
    in property <image> spyrosoft-logo: @image-url("assets/spyrosoft-logo.svg");
    in property <image> dashboard: @image-url("assets/dashboard.svg");
    in property <image> guestos_kylin: @image-url("assets/linux_logo.png");
    in property <image> guestos_kylin_offline: @image-url("assets/power.png");
    in property <image> guestos_kylin_busy: @image-url("assets/linux_busy.png");
    in property <image> vdi_logo: @image-url("assets/vdi_logo.png");
    in property <image> login: @image-url("assets/login_bg.png");
    in property <image> logo: @image-url("assets/logo.png");
}